theme: jekyll-theme-tactile
name: Dennis Chuah

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

footer-links:
  github: 
  rss: Feed

permalink: /:title/



version: v4.0.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
gems:
  - jekyll-sitemap 
  - jekyll-feed 


# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

